# Generated by Django 5.1.7 on 2025-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfoliotransaction_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=13),
        ),
    ]
